version: '3.8'
services:
  web:
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - ./services/web/:/usr/src/app/
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    build: ./services/postgres
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
      - ./services/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    env_file:
      - ./.env.prod.db
    ports:
      - 9877:5432
  nginx:
    build: ./services/nginx
    ports:
      - 1112:80
    depends_on:
      - web
volumes:
  postgres_data_prod:
