name: tests
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build and run containers
      run: |
        docker compose up -d --build
        docker ps -a
        sleep 20

    - name: check web container is running
      run: |
        docker compose ps | grep web | grep Up

    - name: check db container is running
      run: |
        docker compose ps | grep db | grep Up

    - name: check home page returns 200
      run: |
        curl -f http://localhost:1111
